export const MODAL_STATE = Object.freeze({
  NONE: '',
  LOADING: 'LOADING',
  CANCEL_CONFIRMATION: 'CANCEL',
  DELETE_CONFIRMATION: 'DELETE',
  STATUS_ACTIVATE: 'ACTIVATE',
  STATUS_DEACTIVATE: 'DEACTIVATE',
  STATUS_DRAFT: 'DRAFT',
  STATUS_PUBLISH: 'PUBLISH',
  ERROR: 'ERROR',
  SUCCESS: 'SUCCESS',
})
