export const MODAL_STATE = Object.freeze({
  NONE: '',
  LOADING: 'LOADING',
  DELETE_CONFIRMATION: 'DELETE_CONFIRMATION',
  STATUS_ACTIVATE: 'STATUS_ACTIVATE',
  STATUS_DEACTIVATE: 'STATUS_DEACTIVATE',
  STATUS_DRAFT: 'DRAFT',
  STATUS_PUBLISH: 'PUBLISH',
  ERROR: 'ERROR',
  SUCCESS: 'SUCCESS',
})
